### PR TITLE
shuttles, event spawners and kitchen

### PR DESCRIPTION
**Pull request by Pyko1**
added to station

fixes: https://github.com/Carbonhell/Hippie-Rebase/issues/66

### CODE REVIEW

**Comment by Pyko1** [comment]
Added the chefs vender and harvest storage smartfridge to kitchen, renamed chef spawn to cook.

**Comment by Pyko1** [comment]
added couple missing area icons

**Comment by Pyko1** [comment]
Fired the cook, hired a real chef

**Comment by Pyko1** [comment]
adding the sec map fixes DNM

**Comment by Pyko1** [comment]
added the sec map fixes, besides sec disposals which i remade to be more like the rest of the disposals is, and connected wardens office back to disposals as well.

**Comment by Pyko1** [comment]
works with no runtime, aslso sinc ei was too lazy to nuke the original item menu for snack vender it now has.

	products = list(
/obj/item/weapon/storage/bag/tray = 2,
/obj/item/weapon/kitchen/fork = 4,
/obj/item/weapon/reagent_containers/food/drinks/drinkingglass = 4,
/obj/item/weapon/reagent_containers/food/condiment/pack/ketchup = 4,
/obj/item/weapon/reagent_containers/food/condiment/pack/hotsauce = 4,
/obj/item/weapon/reagent_containers/food/condiment/saltshaker = 4,
/obj/item/weapon/reagent_containers/food/condiment/peppermill = 4)
	contraband = list(/obj/item/weapon/sharpener = 1,
/obj/item/weapon/kitchen/knife = 1)

**Comment by SpankMasterson** [comment]
+1 will not divide us

**Comment by McBawbaggings** [comment]
Okay +1

**Pull request merged**
