### PR TITLE
Ports Ninja Fixes

### PR DESCRIPTION
**Pull request by ghost**
Ports my ninja fixes. The fixes move ninja files from their own special snowflake module into events, and compresses it from 20+ files into 9. Somehow this fixed the runtimes. There have been several ninjas on the station since this update with no issues.

### CODE REVIEW

**Comment by ghost** [comment]
I had to make this using the website only, because I was getting permissions issues when I tried to use desktop.

**Comment by tortellinitony** [comment]
you made it in your master branch

**Comment by ghost** [comment]
It's the only pr I intend to put up until I figure out why github desktop won't work for me here.

**Comment by Carbonhell** [comment]
Fix the conflicts

**Pull request closed without merging**
