### PR TITLE
Crew objectives

### PR DESCRIPTION
**Pull request by ghost**
Yada yada

### CODE REVIEW

**Comment by yobob591** [comment]
wow shits getting done what

**Comment by KittyKathy** [comment]
Do you really want crew objectives in the rebase seeing as they had so many issues with it?
Chemist having to make chemicals that are unable to be made like Oxandrolone and Salicyclic Acid.
Mid-round antagonist getting crew objectives and antagonist objectives which means the crew objectives can prevent green text.
Assistants getting a objective to not get tased which is pretty stupid as they don't actually have to do any work and is impossible to stop if security decides to randomly search you.

**Comment by ghost** [comment]
I mean I can remove the assistant objective and change the chemist objective very trivially, not really relevant to the PR.

**Comment by tortellinitony** [comment]
NO no no NO NO even carbon said he didn't want them

**Comment by j-mie** [comment]
We can fix the issues with this post launch.

**Pull request merged**
