### PR TITLE
Ports #1921 from HippieStationCode

### PR DESCRIPTION
**Pull request by Sarcalogo**
https://github.com/HippieStationCode/HippieStation13/pull/1921

### CODE REVIEW

**Comment by banthebantz** [comment]
They already nerfed it by making it irradiate you

**Comment by Sarcalogo** [comment]
That is /tg/'s nerf, not Hippie's nerf.

**Comment by tortellinitony** [comment]
make it not irradiate you then

**Comment by QuarianCommando** [comment]
I thought Hippie's nerf was removing it?

**Comment by KittyKathy** [comment]
No get out with your grudge code bullshit, not only are you nerfing the armor you are effectively removing it to the point where you will almost NEVER see it here is why.
1. The armor is not good anymore halving the activation chance(50% ->25%) and adding a slowdown.
2. The research levels not reachable without special items not always available or using the recently buffed E.X.P.E.R.I-MENTOR like anyone knows or wants to use that.
3. if you get the items for those levels you need materials which means someone needs to mine.

For these reasons you will never see it, who would actually want to work this hard for a nerfed shitty version of the Reactive Teleport Armor when you could make something like a mech/op guns/gear with less effort and be better off.

These are the levels needed for people who don't read the commits but post anyway
`req_tech = list("materials" = 7, "combat" = 6, "powerstorage" = 6, "magnets" = 6, "programming" = 6, "bluespace" = 7) `
bluespace 7 is not easily reachable without items like the abductor baton or the mech teleporter from mining which is a ton of points.

These are the materials from mining to make it
`materials = list(MAT_METAL = 25000, MAT_GLASS = 10000, MAT_SILVER = 20000, MAT_GOLD = 20000, MAT_PLASMA = 6000, MAT_DIAMOND = 2000)`
Nothing not even the Gauss Rifle or Laser Hypercannon require that much material and those things are super lethal one can blow off limbs the other can instantly put you in critical with one shot if used right like shooting down long halls.

**Comment by Uqualm** [comment]
Doesn't matter Kitty Kathy, this is a Hippie rebase, this pull request was accepted years ago by the headmins at the time, which means it was approved and has been part of the game for years. Porting things that already exist on the main code is the entire purpose of the rebase. Don't forget why it is this was removed.

**Comment by banthebantz** [comment]
Kitty Kathy does bring up a very good point though, the TG nerfs is FAR less heavyhanded then our one which literally makes it completely useless (bad balancing).

Also if the rebase is just porting over shit without questions then merge my genetics revert naow!111

**Comment by KittyKathy** [comment]
It was removed because you got butt hurt, I did not forget also just because it is part of hippie code does not mean it has to be ported over if this gets denied consider it a removal from hippie code.
If for some reason this gets accepted, after the rebase I will just make your changes not shitty/probably entirely remove them and do something else with the armor as the RD pretty much has nothing at round start compared to the other head roles.

Also the headmins then and now are different you can't speak for the ones we have now and the old headmins don't really matter much seeing as they are not part of the team or active on git. I am talking about Nokington and Nebyab the two who approved and merged that PR.

It's pretty stupid to just mindlessly port stuff over just because it is part of current hippie code and not talking the time to decide which changes are actually worth adding. I really hope we are not mindlessly porting stuff.

Actually this is not even a port and should need admin input because this is changing something that already exist in the code, this is not adding new content. 
Also there is no real input that they can give because the tg nerfs have not been tested to see if they need further nerfs. Not used once on the actual server and you already want to change it just scream you are butt hurt to everyone.

**Comment by Uqualm** [comment]
I am butthurt, reactive teleport armor is the worst thing that has ever come out of SS13 barring anti-stuns.

**Comment by JamieH** [comment]
Denied - let's leave it for now and see if it gets abused again, We can revisit this if it does.

**Comment by banthebantz** [comment]
KittyKathy is that wall of text meant for me? I never once complained or advocated for the removal of reactive tele armour you nerd.

**Pull request closed without merging**
