### PR TITLE
Laser Eye 

### PR DESCRIPTION
**Pull request by Anderbergst**
:cl: Anderbergst
add: Added new geneticist exclusive traitor item called Laser Eyes DNA Injector to the uplink. For 8tc you can now purchase an injector containing a syndicate modified retrovirus strain that mutates the user's eyes allowing them to project laser bolts at will.
:cl:

### CODE REVIEW

**Comment by Anderbergst** [comment]
WHERE IS TRAVIS?!?

**Comment by yobob591** [comment]
help travis save us

**Comment by KittyKathy** [comment]
Can this be stolen by stealing the geneticist DNA so the whole crew could have it?

**Comment by JohnGinnane** [comment]
Cool

**Comment by Anderbergst** [comment]
I don't think it can be stolen

**Comment by blobbernaut** [comment]
Oh god.

**Comment by ghost** [comment]
amazing
do it
+1

**Comment by Carbonhell** [comment]
+1

**Comment by Swagile** [comment]
+ 1 as long as the code is good

**Comment by dreamcrab** [comment]
+420

**Pull request merged**
