### PR TITLE
Ported Near Crit

### PR DESCRIPTION
**Pull request by JohnGinnane**
This will allow people who have between -50 and 0 health to move every 3 seconds at the expense of some health

### CODE REVIEW

**Comment by JohnGinnane** [comment]
image

I've managed to do the complete opposite. Will need to rewrite this

**Comment by JohnGinnane** [comment]
On second though, to keep my train of thought I'm going to reopen and work it into the correct method

**Comment by Carbonhell** [comment]
any news...?

**Comment by JohnGinnane** [comment]
It's kinda not exactly working. I will look at some more this weekend hopefully

**Comment by JohnGinnane** [comment]
Sorry lads, been unable to look at this due to busy work schedule. Perhaps someone with more time can take care of

**Pull request closed without merging**
